apiVersion : apps/v1
kind: Deployment
metadata:
  name: $(imagerepository) 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $(imagerepository)
  template:
    metadata:
      labels:
        app: $(imagerepository) 
    spec:
      containers:
        - name: $(imagerepository)
          image: $(containerregistry)/$(imagerepository)
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: $(imagerepository)
spec:
  selector:
    app: $(imagerepository)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer