trigger: none
variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'dockersc'
  imageRepository: 'pipelinerepa'
  containerRegistry: 'aksagent.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'pipelinerepogeka-auth'
  kubernetesconnection: 'kubeconnection'
  
stages:

  - stage: powershell
    displayName: Build infrastructure
    jobs:
    - job: Powershell
      displayName: Powershell Infra
      pool:
        name: My-AKS-Pool
      steps:
        - template: powershell.yml
         
            
  - stage: BuildDocker
    displayName: Build docker
    jobs:
    - job: builddocker
      displayName: Build docker
      pool:
        name: Azure Pipelines
      steps:
        - template: dockerbuild.yml

  - stage: DeployDocker
    displayName: Deploy docker
    jobs:
    - job: DeployDocker
      displayName: Deploy docker
      pool:
        name: My-AKS-Pool
      steps:
        - template: dockerdeploy.yml
          