trigger: none

stages:

  - stage: powershell
    displayName: Build infrastructure
    jobs:
    - job: Powershell
      displayName: Powershell Infra
      pool:
        name: My-AKS-Pool
      steps:
        - template: powershell.yml
         
            
  - stage: BuildDocker
    displayName: Build docker
    jobs:
    - job: builddocker
      displayName: Build docker
      pool:
        name: My-AKS-Pool
        variables:
          # Container registry service connection established during pipeline creation
          dockerRegistryServiceConnection: 'dockersc'
          imageRepository: 'mydocimage'
          containerRegistry: 'aksagent.azurecr.io'
          dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
      steps:
        - template: dockerbuild.yml

  - stage: DeployDocker
    displayName: Deploy docker
    jobs:
    - job: DeployDocker
      displayName: Deploy docker
      pool:
        name: My-AKS-Pool
      steps:
        - template: dockerdeploy.yml
          