trigger: none
variables:
  dockerRegistryServiceConnection: 'dockersc'
  imagename: pipelinetest
  containerRegistry: gekaimages.azurecr.io
  dockerfilePath: '**/Dockerfile'

stages:

  - stage: BuildDocker
    displayName: Build and push docker
    jobs:
    - job: docker
      displayName: Build and push docker
      pool:
        name: pipeline-agent
      steps:
        - template: dockerbuild.yml

  - stage: createInfrastucture
    displayName: Build infrastructure
    jobs:
    - job: AzCli
      displayName: Az Cli Infra
      pool:
        name: pipeline-agent
      steps:
       - template: infrastucture.yml

          