---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: deployname
spec:
  replicas: 1
  selector:
    matchLabels:
      containerlabel: labelsformach
  template:
    metadata:
      labels:
        containerlabel: labelsformach
    spec:
      containers:
        - name: justname
          image: gekaimages.azurecr.io/pipelinetest:latest
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: servicename
spec:
  selector:
    containerlabel: labelsformach
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer