---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: deployname
spec:
  replicas: 1
  selector:
    matchLabels:
      containerlabel: labelsformach
  template:
    metadata:
      labels:
        containerlabel: labelsformach
    spec:
      containers:
        - name: justname
          image: gekaimages.azurecr.io/pipelinetest:latest
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: servicename
spec:
  selector:
    containerlabel: labelsformach
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aspnetapp
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "GekaApplicationGatewaySslCert"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: servicename
            port:
              number: 80
        pathType: Exact