---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: $(imagename) 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $(imagename)
  template:
    metadata:
      labels:
        app: $(imagename) 
    spec:
      containers:
        - name: $(imagename)
          image: $(containerRegistry)/$(imagename)
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: $(imagename)
spec:
  selector:
    app: $(imagename)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer