---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: pipelinetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelinetest
  template:
    metadata:
      labels:
        app: pipelinetest
    spec:
      containers:
        - name: pipelinetest
          image: gekaimages.azurecr.io/pipelinetest:latest
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: pipelinetest
spec:
  selector:
    app: pipelinetest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer