apiVersion : apps/v1
kind: Deployment
metadata:
  name: pipelinerepa 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelinerepa
  template:
    metadata:
      labels:
        app: pipelinerepa 
    spec:
      containers:
        - name: pipelinerepa
          image: aksagent.azurecr.io/pipelinerepa
          ports:
          - containerPort: 8080